# Generated by Django 2.1 on 2020-11-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [                   #after writing code in product.models.py run python manage.py makemigrations
        migrations.CreateModel(      # which will automatically populate the code req to make sql table
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image_urls', models.CharField(max_length=2083)),
            ],
        ),
    ]
